#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Joao Pedro Fusco'
        hostname: jpfusco-desktop
        username: joaop
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: "en_US.UTF-8"
    keyboard:
        layout: us
        variant: "intl"
    timezone: "America/Sao_Paulo"   
    packages:
        - git
        - wget
        - curl
        - neofetch
    snaps:
        - name: code
          channel: latest/stable
          classic: true
        - name: postman
          channel: latest/stable
          classic: true
        - name: discord
          channel: latest/stable
          classic: false
    late-commands:
        - curtin in-target -- apt-get autoremove -y
        - |
          curtin in-target -- wget -q https://raw.githubusercontent.com/joaopfusco/ubuntu-autoinstall/refs/heads/main/dev.sh
          curtin in-target -- bash dev.sh
          curtin in-target -- rm dev.sh
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
