#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Joao Pedro Fusco'
        hostname: jpfusco-desktop
        username: joaop
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: "en_US.UTF-8"
    keyboard:
        layout: us
        variant: "intl"
    timezone: "America/Sao_Paulo"   
    packages:
        - git
        - wget
        - curl
        - neofetch
        - docker.io
        - docker-compose
    snaps:
        - name: code
          channel: latest/stable
          classic: false
        - name: postman
          channel: latest/stable
          classic: false
        - name: discord
          channel: latest/stable
          classic: false
    late-commands:
        - curtin in-target -- apt-key adv --fetch-keys https://dl.google.com/linux/linux_signing_key.pub
        - curtin in-target -- sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        - curtin in-target -- apt-get update
        - curtin in-target -- apt-get install -y google-chrome-stable
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
